version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    allow:
      - dependency-type: direct
    groups:
      production:
        patterns:
          - '*'
      dev:
        dependency-type: development
        patterns:
          - '*'
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: direct
    groups:
      pip-group:
        patterns:
          - '*'
